image: ubuntu:18.04

before_script:

    # install dependancies
    - apt-get update -yq
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -yq
        build-essential
        pkg-config
        cmake
        git
        jackd1
        libjack-dev
        libsndfile1-dev
        libasound2-dev
        libavahi-client-dev
        libxt-dev
        libicu-dev
        libreadline6-dev
        libfftw3-dev
        libudev-dev

    # build SuperCollider
    - git clone
        --branch master
        --depth 1
        --recurse-submodules
        https://github.com/supercollider/supercollider.git
    - cd supercollider && mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DSC_EL=OFF -DSC_QT=OFF -DSC_IDE=OFF ..
    - cmake --build . --target install -- -j$(nproc)
    - cd ../../

    # build sc3-plugins
    - git clone
        --branch master
        --depth 1
        --recurse-submodules
        https://github.com/supercollider/sc3-plugins.git
    - cd sc3-plugins && mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DSC_PATH=../../supercollider ..
    - cmake --build . --target install -- -j$(nproc)
    - cd ../../

    - ldconfig
    - rm -rf sc3-plugins
    - rm -rf supercollider

    # install SATIE and dependant quarks
    # be sure to uninstall UnitTesting after it gets installed automatically
    - sclang ci/install_quarks.scd

test:
    script:
        - jackd --no-realtime -d dummy -r 48000 -p 1024 &
        - sleep 20
        - sclang ci/run_tests.scd
        - echo "Success!"
